### ISSUE TITLE
[Bug]: Keynote Manager and Autodesk Desktop Connector Issues

### ISSUE THREAD

**Issue by ChBrownTheThird** [pyrevitlabs/pyRevit#2596]
### ✈ Pre-Flight checks

- [x] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [x] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [x] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [x] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [x] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

The Issue:
My teams are running the latest versions of Revit 2025, Autodesk Desktop Connector, and pyRevit. Our project are collaborated with ACC, including the keynote file. When using the Keynote Manager, we get the following message, "This model is using a keynote file that seems to be managed by Autodesk Desktop Connector (ADC). But ADC is not running, or is not installed. Please install/run the ADC and open the keynote manager again". However ADC is installed and running. This doesn't happen with any other version of Revit.

### ⌨ Error/Debug Message

```shell
This model is using a keynote file that seems to be managed by Autodesk Desktop Connector (ADC). But ADC is not running, or is not installed. Please install/run the ADC and open the keynote manager again
```

### ♻️ To Reproduce

1. Upload a keynote file to an ACC folder that is shared with Autodesk Desktop Connector.
2. Ensure ADC is running and the project is selected and synched.
3. Open Revit 2025, Start a project from the ACC folder and load the keynote file.
4. Open the Keynote Manager. 

### ⏲️ Expected behavior

The expected behavior is that when ADC is running, the Keynote Manager will open the shared keynote. 

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Branch: "master" | Version: "5.0.1.25051+1239" | Path: "C:\Program Files\pyRevit-Master"
==> Attachments
master | Product: "2025 First Customer Ship" | Engine: DEFAULT (2712) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2024.2" | Engine: DEFAULT (2712) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
master | Product: "2023.1.3" | Engine: DEFAULT (2712) | Path: "C:\Program Files\pyRevit-Master" | AllUsers
==> Installed Extensions
==> Default Extension Search Path
C:\Users\clark.brown\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/pyrevitlabs/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
2025 First Customer Ship | Version: 25.0.2.419 | Build: 20240307_1300(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2025\"
2024.2 | Version: 24.2.0.63 | Build: 20231029_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2024\"
2023.1.3 | Version: 23.1.30.97 | Build: 20230828_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.22631]
Executing User: BDGARCHITECTS\clark.brown
Active User: BDGARCHITECTS\clark.brown
Admin Access: Yes
%APPDATA%: "C:\Users\clark.brown\AppData\Roaming"
Latest Installed .Net Framework: 9.0.1
Installed .Net Target Packs: v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.7.2 v4.8 v4.X
Installed .Net-Core Target Packs: v9.0.102
pyRevit CLI v5.0.1.25051+1239.a19f9a76cf00d7256cf522f5ec874fea9dd0baa8
```

### Additional context

![Image](https://github.com/user-attachments/assets/0e30b106-341e-4195-989f-3a5dbea4997c)

**Comment by micahschneider** [comment]
Our office just switched to Revit 2025, and this issue is very unfortunate. 
Looking at [this forum](https://discourse.pyrevitlabs.io/t/wip-build-for-2025-and-desktop-connector/8022) from October, it sounds like there is Backlog of tickets about the keynote manager. 

Hopefully this moves to the front of the list!

**Comment by zsenarchitect** [comment]
i would like to upvote fixing this issue!

**Comment by jmcouffin** [comment]
I am in touch with Autodesk to see how much we can fix the whole thing
It seems that there are many issues. One being that you should not use the DC to store the keynote file, as none of the test I made gave a conclusive possibility to use the keynote file this way:

open the keynote file through the local copy from docs in:
- Notepad, the file is not locked and changes are not reconciled if two people edit the file at the same time or so
- word, the file is locked and no one else can edit it at the same time.

It feels like a dead end.

**Comment by ChBrownTheThird** [comment]
Hi Jean-Marc!

Thanks for your reply. Yes, I agree that DC should not be used to store the keynote file. However, we must store the keynote on ACC for sharing with consultants and international team members. The tool opens the keynote file perfectly in every other version of Revit, whether hosted locally or on ACC via DC. The issue is that in Revit 2025, the tool doesn’t see DC as being installed or running, at any point, and will not run as it is catching that error and ending the script.

I would be glad to help in any way I can to find and remedy the issue.

**Comment by jmcouffin** [comment]
https://github.com/pyrevitlabs/pyRevit/blob/85662fff4dad05857c179b71d88b6d661465f57a/extensions/pyRevitTools.extension/pyRevit.tab/Drawing%20Set.panel/Keynotes.pushbutton/script.py#L585

Here are my findings so far:
After way too much debugging, I found that the keynote manager is calling directly the Desktop Connector Service function from within Revit 2025 (.NET8 Core) while the dll being called seems to rely on .net 4.0 framework, all the subsequent function are refering to the same dll, this is why it is failing.

I do not have the time to dig deeper and fix this right now as I am first trying to fix the issue of concurrent access to the keynote file being broken (checking with AUTODESK people, it takes me more time to meet and schedule calls)

**Comment by jmcouffin** [comment]
@ChBrownTheThird latest wip should fix it.
Please test and report here if anything wrong.

**Comment by ChBrownTheThird** [comment]
Hi Jean-Marc! I will test it out today. Thank you for your help. I understand how much work this must be.



Best regards,



[Logo  Description automatically generated]

Clark H. Brown III

Director – Digital Design

400 N. Ashley Drive, Suite 600

Tampa, Florida 33602

office: 813.323.9233 x233

www.bdgllp.com<http://www.bdgllp.com/>






________________________________

**Comment by cadengabel** [comment]
Hi Jean and ChBrown, this is actually my first day in pyRevit ever (super awesome so far and cannot believe I am just now getting to try it out) but was eager to try out the manage keynotes within pyRevit. I believe I downloaded the latest package, but I'm still getting that ADC error. My laptop has SentinelOne installed though - does that need to be deleted?

**Comment by jmcouffin** [comment]
@CadenG18 are you sure you got the latest one? 

![Image](https://github.com/user-attachments/assets/3abed64c-05d0-4978-8550-727c9da712f7)

**Comment by CadenG18** [comment]
Yes I have the latest one, but I also get this error every single time I open a workshared file for the first time. I have the desktop connector installed and running but Revit seems to think desktop connector is not working/running. I might have some other issue going on that has nothing to do with pyrevit

![Image](https://github.com/user-attachments/assets/f0a1d314-f7b1-438a-bdcf-55e2cb77ef78)

**Comment by m5james** [comment]
@jmcouffin Been tracking this closely - attempted the most recent WIP Installer and upon launching the keynote manager in R25 I'm receiving this error window: 

![Image](https://github.com/user-attachments/assets/8670b8c7-91a5-4fda-9d00-24b581eb0efd)

**Comment by CadenG18** [comment]
Update on my end - it works for me now! I had to get the latest version of Desktop Connector and had IT do a few SentinelOne exclusions.

**Comment by jmcouffin** [comment]
> [@jmcouffin](https://github.com/jmcouffin) Been tracking this closely, thank you very much for your effort - attempted the most recent WIP Installer and upon launching the keynote manager in R25 I'm receiving this error window:

Yes @m5james a bug I introduced a day or two ago in another pr, not related
I will fix it in a bit and new wip will be alllllll good.

**Comment by jmcouffin** [comment]
@m5james Latest wip should fix it. (I just pushed the button, wait another 20min to get the WIP installer)
- uninstall, 
- install latest wip
- go get and popsicle (just in case someone thinks I am an AI 😄 )

**Comment by PAYAM2000** [comment]
Hello there. 
I have installed the pyRevit v5.1.0 and ADC 16.12.0 on Revit 2025.4, and I continue having "keynote file seems to be managed by Autodesk Desktop connector..." error.  What is the fix?!

**Comment by PAYAM2000** [comment]
> [@jmcouffin](https://github.com/jmcouffin) Been tracking this closely, thank you very much for your effort - attempted the most recent WIP Installer and upon launching the keynote manager in R25 I'm receiving this error window:
> 
> Error when Launching Keynote Manager: ![Image](https://github.com/user-attachments/assets/8670b8c7-91a5-4fda-9d00-24b581eb0efd)
> 
> Error upon launching R25: ![Image](https://github.com/user-attachments/assets/1ae0c51f-5ccb-457c-9092-9a1d20959bbc)

I made it to this error. How did you fix it from here.

**Comment by jmcouffin** [comment]
> > [@jmcouffin](https://github.com/jmcouffin) Been tracking this closely, thank you very much for your effort - attempted the most recent WIP Installer and upon launching the keynote manager in R25 I'm receiving this error window:
> > Error when Launching Keynote Manager: ![Image](https://github.com/user-attachments/assets/8670b8c7-91a5-4fda-9d00-24b581eb0efd)
> > Error upon launching R25: ![Image](https://github.com/user-attachments/assets/1ae0c51f-5ccb-457c-9092-9a1d20959bbc)
> 
> I made it to this error. How did you fix it from here.

Install the latest wip installer. Not the la test release.
The orange button here https://www.pyrevitlabs.io/
